name: Build and Release LaTeX Documents

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        document:
          - name: template

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build auftragskl채rung for ${{matrix.document.name}}
      uses: xu-cheng/latex-action@v2
      with:
        root_file: auftragskl채rung.tex
        working_directory: src/${{matrix.document.name}}
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
        args: >
          -synctex=1
          -interaction=nonstopmode
          -file-line-error
          -outdir=../../../build/${{matrix.document.name}}

    - name: Build eidestattliche_erkl채rung for ${{matrix.document.name}}
      uses: xu-cheng/latex-action@v2
      with:
        root_file: eidestattliche_erkl채rung.tex
        working_directory: src/${{matrix.document.name}}
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
        args: >
          -synctex=1
          -interaction=nonstopmode
          -file-line-error
          -outdir=../../../build/${{matrix.document.name}}

    - name: Build selbstreflexion for ${{matrix.document.name}}
      uses: xu-cheng/latex-action@v2
      with:
        root_file: selbstreflexion.tex
        working_directory: src/${{matrix.document.name}}
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
        args: >
          -synctex=1
          -interaction=nonstopmode
          -file-line-error
          -outdir=../../../build/${{matrix.document.name}}

    - name: Build transferleistung for ${{matrix.document.name}}
      uses: xu-cheng/latex-action@v2
      with:
        root_file: transferleistung.tex
        working_directory: src/${{matrix.document.name}}
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
        args: >
          -synctex=1
          -interaction=nonstopmode
          -file-line-error
          -outdir=../../../build/${{matrix.document.name}}

    - name: Upload artifacts for ${{ matrix.document.name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.document.name }} PDFs
        path: build/${{ matrix.document.name }}/*

  release:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        document:
          - name: template
    steps:
    - name: Download artifacts for ${{ matrix.document.name }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.document.name }} PDFs

    - name: Upload ${{ matrix.document.name }} bundle to GitHub Release
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: "LaTeX Documents"
        body: |
          This release contains the latest compiled LaTeX documents, including auxiliary files.
        draft: false
        prerelease: false
        replacesArtifacts: true
        allowUpdates: true
        artifacts: |
          build/${{ matrix.document.name }}/*
